# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  gantryX:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
    min_position: 0.0
    max_position: 1.75
  gantryY:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
    min_position: -0.5
    max_position: 0.5
  gantryZ:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
    min_position: 0.0
    max_position: 0.625 
  gantryYAW:
    has_velocity_limits: true
    max_velocity: 3.1415
    has_acceleration_limits: true
    max_acceleration: 3.1415
    min_position: -3.1415
    max_position: 3.1415
  gantryPITCH:
    has_velocity_limits: true
    max_velocity: 3.1415 #6.2831
    has_acceleration_limits: true
    max_acceleration: 3.1415 #6.2831
    min_position: -1.5707
    max_position: 1.5707
  gantryROLL:
    has_velocity_limits: true
    max_velocity: 3.1415 #6.2831
    has_acceleration_limits: true
    max_acceleration: 3.1415 #6.2831
    min_position: -3.1415
    max_position: 3.1415
  slider_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
    min_position: -0.01
    max_position: 0.19